export const constants = {
  CART: {
    ADD_TO_CART: "ADD_TO_CART",
    DELETE_FROM_CART: "DELETE_FROM_CART",
    UPDATE_CART: "UPDATE_CART",
    UPDATE_PRODUCT_CART_QUANTITY: "UPDATE_PRODUCT_CART_QUANTITY"
  },
  TASKS: {
    DECREMENT: "DECREMENT",
    INCREMENT: "INCREMENT"
  }
};
