export const constants = {
  CART: {
    ADD_TO_CART: "ADD_TO_CART",
    DELETE_FROM_CART: "DELETE_FROM_CART",
    UPDATE_CART: "UPDATE_CART",
    UPDATE_PRODUCT_CART_QUANTITY: "UPDATE_PRODUCT_CART_QUANTITY",
    CLEAR_CART: "CLEAR_CART",
  },
  TASKS: {
    DECREMENT: "DECREMENT",
    INCREMENT: "INCREMENT",
  },
  USER: {
    ADD_USER_STORE: "ADD_USER_STORE",
    REMOVE_USER_STORE: "REMOVE_USER_STORE",
    UPDATE_USER_STORE: "UPDATE_USER_STORE",
  },
};
